- name: foodapp setup
  hosts: web01
  become: yes
  tasks:
    - name: Install https & git
      ansible.builtin.yum:
        name: 
          - httpd
          - git
        state: present
    - name: Start service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
    - name: Clone a github repository
      git:
        repo: https://github.com/saiurakrishna/food-app.git
        dest: /var/www/html/
        clone: yes
        update: yes
    - name: Start service
      ansible.builtin.service:
        name: httpd
        state: restarted
